# Generated by Django 2.0.2 on 2018-02-22 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='originally_published_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 22, 16, 52, 54, 555509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='originally_published_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 22, 16, 52, 54, 556621, tzinfo=utc)),
        ),
    ]
